// Code generated by internal/codegen/codesgen. DO NOT EDIT.
//
// Source: docs/reference/refusal-codes.md

// Package codes is the closed refusal vocabulary.
//
// A code not in the document is not a code. It may not be narrowed, merged with
// another, or invented locally for a listed cause, and a client that meets one it
// does not recognise surfaces it verbatim rather than folding it into another's
// meaning. Generating this package from the document is what makes the closure
// mechanical: a handler cannot name a code the vocabulary does not carry.
package codes

// Code is a stable machine-readable refusal name, carried as detail.code.
type Code string

// Kind says which party raises a code.
type Kind uint8

const (
	// KindServer codes are raised by the server, against a request.
	KindServer Kind = iota
	// KindClient codes are raised by a device against bytes it pulled, never by
	// the server. They are here because the vocabulary is shared.
	KindClient
)

// Spec is what the document records about one code.
type Spec struct {
	Code Code
	Kind Kind
	// Statuses is every HTTP status this code is raised under, ascending. Empty
	// for client codes, which never travel on a response.
	Statuses []int
	// Deterministic reports whether a retry can change the outcome. A client
	// terminalises a deterministic refusal rather than re-attempting it for ever.
	// Defined for server codes.
	Deterministic bool
	// Where is the layer that specifies the rule.
	Where string
}

// Server codes.
const (
	// AdmissionRefused: POST /v1/members
	AdmissionRefused Code = "admission_refused"
	// AlreadyRevoked: POST .../ops revoke, revoke_delegation
	AlreadyRevoked Code = "already_revoked"
	// AmendIdAlreadyUsed: POST .../ops amend
	AmendIdAlreadyUsed Code = "amend_id_already_used"
	// AuthorChainConflict: POST .../ops
	AuthorChainConflict Code = "author_chain_conflict"
	// AuthorKeyClassMismatch: POST .../ops
	AuthorKeyClassMismatch Code = "author_key_class_mismatch"
	// AuthorMemberMismatch: POST .../ops
	AuthorMemberMismatch Code = "author_member_mismatch"
	// BadGrantSignature: POST .../ops grant
	BadGrantSignature Code = "bad_grant_signature"
	// BadMemberChallenge: POST /v1/members/{m}/token
	BadMemberChallenge Code = "bad_member_challenge"
	// BadRevokeSignature: POST .../ops revoke
	BadRevokeSignature Code = "bad_revoke_signature"
	// BadRootSignature: POST .../ops control; POST /v1/members
	BadRootSignature Code = "bad_root_signature"
	// BadVaultSignature: PUT .../vault
	BadVaultSignature Code = "bad_vault_signature"
	// BatchTooLarge: POST .../ops
	BatchTooLarge Code = "batch_too_large"
	// CertGranterMismatch: POST .../ops grant, revoke
	CertGranterMismatch Code = "cert_granter_mismatch"
	// CertKeyMismatch: POST .../ops genesis, register; POST /v1/members
	CertKeyMismatch Code = "cert_key_mismatch"
	// CertMemberMismatch: POST .../ops genesis, register, amend; POST /v1/members
	CertMemberMismatch Code = "cert_member_mismatch"
	// CertRootPkMismatch: POST .../ops handover; POST /v1/members
	CertRootPkMismatch Code = "cert_root_pk_mismatch"
	// CertWorkspaceMismatch: POST .../ops control
	CertWorkspaceMismatch Code = "cert_workspace_mismatch"
	// ControlChainBreak: POST .../ops control
	ControlChainBreak Code = "control_chain_break"
	// DelegatePkInUse: POST .../ops delegate
	DelegatePkInUse Code = "delegate_pk_in_use"
	// DelegationIdAlreadyUsed: POST .../ops delegate
	DelegationIdAlreadyUsed Code = "delegation_id_already_used"
	// DuplicateKeywrapMember: PUT .../keywraps
	DuplicateKeywrapMember Code = "duplicate_keywrap_member"
	// EncryptedControlOp: POST .../ops
	EncryptedControlOp Code = "encrypted_control_op"
	// EncryptedPruneOp: POST .../ops
	EncryptedPruneOp Code = "encrypted_prune_op"
	// EncryptedServerReadOp: POST .../ops
	EncryptedServerReadOp Code = "encrypted_server_read_op"
	// EnvelopeTooShort: POST .../ops
	EnvelopeTooShort Code = "envelope_too_short"
	// ExtClassAlreadyBound: POST .../ops ext_binding
	ExtClassAlreadyBound Code = "ext_class_already_bound"
	// ExtClassNotActive: POST .../ops extension classes
	ExtClassNotActive Code = "ext_class_not_active"
	// ExtClassNotBound: POST .../ops ext_binding
	ExtClassNotBound Code = "ext_class_not_bound"
	// ExtClassNotEnabled: POST .../ops ext_binding
	ExtClassNotEnabled Code = "ext_class_not_enabled"
	// ExtNameMismatch: POST .../ops ext_binding, extension classes
	ExtNameMismatch Code = "ext_name_mismatch"
	// GenesisNotFirst: POST .../ops genesis
	GenesisNotFirst Code = "genesis_not_first"
	// GrantIdAlreadyUsed: POST .../ops grant
	GrantIdAlreadyUsed Code = "grant_id_already_used"
	// HardPruneTargetIsPrune: POST .../ops hard_prune
	HardPruneTargetIsPrune Code = "hard_prune_target_is_prune"
	// HardPruneTargetNotReprised: POST .../ops hard_prune
	HardPruneTargetNotReprised Code = "hard_prune_target_not_reprised"
	// InvalidBodyLength: POST .../ops server-read classes
	InvalidBodyLength Code = "invalid_body_length"
	// InvalidCredential: any authenticated route
	InvalidCredential Code = "invalid_credential"
	// InvalidRefreshToken: POST /v1/members/{m}/token/refresh
	InvalidRefreshToken Code = "invalid_refresh_token"
	// KexKeyIdNotRegistered: PUT .../keywraps
	KexKeyIdNotRegistered Code = "kex_key_id_not_registered"
	// KeyEpochStale: POST .../ops
	KeyEpochStale Code = "key_epoch_stale"
	// KeyEpochUnknown: POST .../ops
	KeyEpochUnknown Code = "key_epoch_unknown"
	// KeyIdNotDerivedFromSignPk: POST /v1/members
	KeyIdNotDerivedFromSignPk Code = "key_id_not_derived_from_sign_pk"
	// KeywrapAlreadyWritten: PUT .../keywraps
	KeywrapAlreadyWritten Code = "keywrap_already_written"
	// KeywrapDigestMismatch: PUT .../keywraps
	KeywrapDigestMismatch Code = "keywrap_digest_mismatch"
	// KeywrapRequiresOwner: PUT .../keywraps
	KeywrapRequiresOwner Code = "keywrap_requires_owner"
	// MalformedBase64: POST .../ops
	MalformedBase64 Code = "malformed_base64"
	// MalformedControlPayload: POST .../ops control; POST /v1/members
	MalformedControlPayload Code = "malformed_control_payload"
	// MalformedEscrowWrap: PUT .../keywraps
	MalformedEscrowWrap Code = "malformed_escrow_wrap"
	// MalformedExtBindingPayload: POST .../ops ext_binding
	MalformedExtBindingPayload Code = "malformed_ext_binding_payload"
	// MalformedKexKeyId: PUT .../keywraps
	MalformedKexKeyId Code = "malformed_kex_key_id"
	// MalformedKexPk: POST /v1/members
	MalformedKexPk Code = "malformed_kex_pk"
	// MalformedKeyEpoch: PUT .../keywraps
	MalformedKeyEpoch Code = "malformed_key_epoch"
	// MalformedKeyId: POST /v1/members
	MalformedKeyId Code = "malformed_key_id"
	// MalformedKeywrap: PUT .../keywraps
	MalformedKeywrap Code = "malformed_keywrap"
	// MalformedKeywrapDigest: PUT .../keywraps
	MalformedKeywrapDigest Code = "malformed_keywrap_digest"
	// MalformedPrunePayload: POST .../ops 0x81
	MalformedPrunePayload Code = "malformed_prune_payload"
	// MalformedRequest: any route
	MalformedRequest Code = "malformed_request"
	// MalformedRoleTable: POST .../ops role_table
	MalformedRoleTable Code = "malformed_role_table"
	// MalformedRootPk: PUT .../vault; POST /v1/members; POST .../ops delegate, handover
	MalformedRootPk Code = "malformed_root_pk"
	// MalformedSignPk: POST /v1/members
	MalformedSignPk Code = "malformed_sign_pk"
	// MalformedVaultBlob: PUT .../vault
	MalformedVaultBlob Code = "malformed_vault_blob"
	// MalformedVaultSignature: PUT .../vault
	MalformedVaultSignature Code = "malformed_vault_signature"
	// MalformedVaultVersion: PUT .../vault
	MalformedVaultVersion Code = "malformed_vault_version"
	// MemberChallengeRateLimited: POST /v1/members/{m}/challenge
	MemberChallengeRateLimited Code = "member_challenge_rate_limited"
	// MemberIdAlreadyRegistered: POST /v1/members
	MemberIdAlreadyRegistered Code = "member_id_already_registered"
	// MemberKindForbidden: POST .../ops grant
	MemberKindForbidden Code = "member_kind_forbidden"
	// MemberQuotaExhausted: POST .../ops
	MemberQuotaExhausted Code = "member_quota_exhausted"
	// MemberRegisterNotFirst: POST .../ops genesis, register
	MemberRegisterNotFirst Code = "member_register_not_first"
	// MissingKeywrapDigest: PUT .../keywraps
	MissingKeywrapDigest Code = "missing_keywrap_digest"
	// NoLiveGrant: device routes
	NoLiveGrant Code = "no_live_grant"
	// NoRegistration: Workspace-scoped device routes
	NoRegistration Code = "no_registration"
	// NoVaultRecord: GET .../vault
	NoVaultRecord Code = "no_vault_record"
	// NonZeroPadding: POST .../ops server-read classes
	NonZeroPadding Code = "non_zero_padding"
	// NotFound: any unrouted path, including a misshapen locator
	NotFound Code = "not_found"
	// OwnerGrantRequiresRoot: POST .../ops grant
	OwnerGrantRequiresRoot Code = "owner_grant_requires_root"
	// OwnerRevokeRequiresRoot: POST .../ops revoke
	OwnerRevokeRequiresRoot Code = "owner_revoke_requires_root"
	// PayloadOverrunsBody: POST .../ops server-read classes
	PayloadOverrunsBody Code = "payload_overruns_body"
	// PruneDuplicateTarget: POST .../ops 0x81
	PruneDuplicateTarget Code = "prune_duplicate_target"
	// PruneExtNameMismatch: POST .../ops prune_ext
	PruneExtNameMismatch Code = "prune_ext_name_mismatch"
	// PruneExtWrongClass: POST .../ops prune_ext
	PruneExtWrongClass Code = "prune_ext_wrong_class"
	// PruneRepriseNotFound: POST .../ops prune
	PruneRepriseNotFound Code = "prune_reprise_not_found"
	// PruneTargetAlreadyReprised: POST .../ops prune, prune_ext
	PruneTargetAlreadyReprised Code = "prune_target_already_reprised"
	// PruneTargetAttestationMismatch: POST .../ops 0x81
	PruneTargetAttestationMismatch Code = "prune_target_attestation_mismatch"
	// PruneTargetIsControl: POST .../ops prune, prune_ext
	PruneTargetIsControl Code = "prune_target_is_control"
	// PruneTargetIsItsOwnReprise: POST .../ops prune
	PruneTargetIsItsOwnReprise Code = "prune_target_is_its_own_reprise"
	// PruneTargetIsPrune: POST .../ops prune, prune_ext
	PruneTargetIsPrune Code = "prune_target_is_prune"
	// PruneTargetIsServerRead: POST .../ops prune, prune_ext
	PruneTargetIsServerRead Code = "prune_target_is_server_read"
	// PruneTargetNotFound: POST .../ops 0x81
	PruneTargetNotFound Code = "prune_target_not_found"
	// PruneTargetsEmpty: POST .../ops 0x81
	PruneTargetsEmpty Code = "prune_targets_empty"
	// PruneTargetsTooMany: POST .../ops 0x81
	PruneTargetsTooMany Code = "prune_targets_too_many"
	// RequestTooLarge: any route
	RequestTooLarge Code = "request_too_large"
	// RoleForbidsOpClass: POST .../ops
	RoleForbidsOpClass Code = "role_forbids_op_class"
	// RoleForbidsPruneType: POST .../ops 0x81
	RoleForbidsPruneType Code = "role_forbids_prune_type"
	// RotateEpochConflict: POST .../ops rotate
	RotateEpochConflict Code = "rotate_epoch_conflict"
	// RotateNotMaterialised: PUT .../keywraps
	RotateNotMaterialised Code = "rotate_not_materialised"
	// StoreUnavailable: any route — GET /health/db is where you ask for it
	StoreUnavailable Code = "store_unavailable"
	// TruncatedEnvelope: POST .../ops
	TruncatedEnvelope Code = "truncated_envelope"
	// UnknownDelegation: POST .../ops revoke_delegation
	UnknownDelegation Code = "unknown_delegation"
	// UnknownGrant: POST .../ops revoke
	UnknownGrant Code = "unknown_grant"
	// UnknownGrantee: POST .../ops grant
	UnknownGrantee Code = "unknown_grantee"
	// UnknownKeywrapMember: PUT .../keywraps
	UnknownKeywrapMember Code = "unknown_keywrap_member"
	// UnknownMember: POST /v1/members/{m}/challenge
	UnknownMember Code = "unknown_member"
	// UnknownMemberKind: POST .../ops genesis, register; POST /v1/members
	UnknownMemberKind Code = "unknown_member_kind"
	// UnknownRequestField: any versioned route
	UnknownRequestField Code = "unknown_request_field"
	// UnknownRole: POST .../ops grant
	UnknownRole Code = "unknown_role"
	// UnsupportedContractVersion: any version-shaped path
	UnsupportedContractVersion Code = "unsupported_contract_version"
	// UnsupportedControlType: POST .../ops control
	UnsupportedControlType Code = "unsupported_control_type"
	// UnsupportedExtBindingType: POST .../ops ext_binding
	UnsupportedExtBindingType Code = "unsupported_ext_binding_type"
	// UnsupportedOpClass: POST .../ops
	UnsupportedOpClass Code = "unsupported_op_class"
	// UnsupportedPruneType: POST .../ops 0x81
	UnsupportedPruneType Code = "unsupported_prune_type"
	// UnsupportedSuite: POST .../ops
	UnsupportedSuite Code = "unsupported_suite"
	// VaultFetchRateLimited: GET .../vault
	VaultFetchRateLimited Code = "vault_fetch_rate_limited"
	// VaultRequiresGenesis: PUT .../vault first write
	VaultRequiresGenesis Code = "vault_requires_genesis"
	// VaultVersionRegression: PUT .../vault
	VaultVersionRegression Code = "vault_version_regression"
	// WorkspaceMismatch: POST .../ops
	WorkspaceMismatch Code = "workspace_mismatch"
	// WorkspaceNotCreated: POST .../ops; POST /v1/members
	WorkspaceNotCreated Code = "workspace_not_created"
	// WorkspaceNotReachable: POST .../ops genesis; POST /v1/members
	WorkspaceNotReachable Code = "workspace_not_reachable"
	// WorkspaceQuotaExhausted: POST .../ops
	WorkspaceQuotaExhausted Code = "workspace_quota_exhausted"
)

// Client codes. Raised by a device against bytes it pulled, never by the server.
const (
	// BadSignature: the envelope's signature does not verify
	BadSignature Code = "bad_signature"
	// ControlTypeNotServed: a load-bearing control type this reader does not serve; authority derivation stops at that position, and everything derived below it stands
	ControlTypeNotServed Code = "control_type_not_served"
	// UnknownAuthorKey: the envelope's author_key_id resolves to no key in force for that device at that op's position
	UnknownAuthorKey Code = "unknown_author_key"
	// AeadFailure: the body did not open under the epoch key
	AeadFailure Code = "aead_failure"
	// PlaintextAtEncryptedEpoch: unsealed content at a log position after the Workspace's first rotate — or at any position, where epoch 0 is keyed
	PlaintextAtEncryptedEpoch Code = "plaintext_at_encrypted_epoch"
)

// Signal close codes. A client's reconnect logic branches on these exact
// numbers, so they are protocol.
const (
	CloseProtocolError = 4400
	CloseInvalidToken  = 4401
	CloseNoMembership  = 4403
)

// All is every code the document carries, server codes first, each group in
// document order.
var All = []Spec{
	{Code: AdmissionRefused, Kind: KindServer, Statuses: []int{403}, Deterministic: true, Where: "Identity"},
	{Code: AlreadyRevoked, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: AmendIdAlreadyUsed, Kind: KindServer, Statuses: []int{409}, Deterministic: true, Where: "Authority"},
	{Code: AuthorChainConflict, Kind: KindServer, Statuses: []int{409}, Deterministic: false, Where: "Log"},
	{Code: AuthorKeyClassMismatch, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: AuthorMemberMismatch, Kind: KindServer, Statuses: []int{403}, Deterministic: true, Where: "Log"},
	{Code: BadGrantSignature, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: BadMemberChallenge, Kind: KindServer, Statuses: []int{401, 422}, Deterministic: true, Where: "Identity"},
	{Code: BadRevokeSignature, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: BadRootSignature, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: BadVaultSignature, Kind: KindServer, Statuses: []int{403}, Deterministic: true, Where: "Keys"},
	{Code: BatchTooLarge, Kind: KindServer, Statuses: []int{413}, Deterministic: true, Where: "Log"},
	{Code: CertGranterMismatch, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: CertKeyMismatch, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: CertMemberMismatch, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: CertRootPkMismatch, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: CertWorkspaceMismatch, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: ControlChainBreak, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: DelegatePkInUse, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: DelegationIdAlreadyUsed, Kind: KindServer, Statuses: []int{409}, Deterministic: true, Where: "Authority"},
	{Code: DuplicateKeywrapMember, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Keys"},
	{Code: EncryptedControlOp, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Keys"},
	{Code: EncryptedPruneOp, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Keys"},
	{Code: EncryptedServerReadOp, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Keys"},
	{Code: EnvelopeTooShort, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: ExtClassAlreadyBound, Kind: KindServer, Statuses: []int{409}, Deterministic: false, Where: "Log"},
	{Code: ExtClassNotActive, Kind: KindServer, Statuses: []int{422}, Deterministic: false, Where: "Log"},
	{Code: ExtClassNotBound, Kind: KindServer, Statuses: []int{422}, Deterministic: false, Where: "Log"},
	{Code: ExtClassNotEnabled, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: ExtNameMismatch, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: GenesisNotFirst, Kind: KindServer, Statuses: []int{409}, Deterministic: true, Where: "Authority"},
	{Code: GrantIdAlreadyUsed, Kind: KindServer, Statuses: []int{409}, Deterministic: true, Where: "Authority"},
	{Code: HardPruneTargetIsPrune, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: HardPruneTargetNotReprised, Kind: KindServer, Statuses: []int{422}, Deterministic: false, Where: "Log"},
	{Code: InvalidBodyLength, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: InvalidCredential, Kind: KindServer, Statuses: []int{401}, Deterministic: true, Where: "Identity"},
	{Code: InvalidRefreshToken, Kind: KindServer, Statuses: []int{401}, Deterministic: true, Where: "Identity"},
	{Code: KexKeyIdNotRegistered, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Keys"},
	{Code: KeyEpochStale, Kind: KindServer, Statuses: []int{409}, Deterministic: false, Where: "Keys"},
	{Code: KeyEpochUnknown, Kind: KindServer, Statuses: []int{409}, Deterministic: false, Where: "Keys"},
	{Code: KeyIdNotDerivedFromSignPk, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Identity"},
	{Code: KeywrapAlreadyWritten, Kind: KindServer, Statuses: []int{409}, Deterministic: true, Where: "Keys"},
	{Code: KeywrapDigestMismatch, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Keys"},
	{Code: KeywrapRequiresOwner, Kind: KindServer, Statuses: []int{403}, Deterministic: false, Where: "Keys"},
	{Code: MalformedBase64, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: MalformedControlPayload, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: MalformedEscrowWrap, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Keys"},
	{Code: MalformedExtBindingPayload, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: MalformedKexKeyId, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Keys"},
	{Code: MalformedKexPk, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Identity"},
	{Code: MalformedKeyEpoch, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Keys"},
	{Code: MalformedKeyId, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Identity"},
	{Code: MalformedKeywrap, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Keys"},
	{Code: MalformedKeywrapDigest, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Keys"},
	{Code: MalformedPrunePayload, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: MalformedRequest, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Compat"},
	{Code: MalformedRoleTable, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: MalformedRootPk, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Keys"},
	{Code: MalformedSignPk, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Identity"},
	{Code: MalformedVaultBlob, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Keys"},
	{Code: MalformedVaultSignature, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Keys"},
	{Code: MalformedVaultVersion, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Keys"},
	{Code: MemberChallengeRateLimited, Kind: KindServer, Statuses: []int{429}, Deterministic: false, Where: "Identity"},
	{Code: MemberIdAlreadyRegistered, Kind: KindServer, Statuses: []int{409}, Deterministic: true, Where: "Identity"},
	{Code: MemberKindForbidden, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: MemberQuotaExhausted, Kind: KindServer, Statuses: []int{402}, Deterministic: false, Where: "Log"},
	{Code: MemberRegisterNotFirst, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: MissingKeywrapDigest, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Keys"},
	{Code: NoLiveGrant, Kind: KindServer, Statuses: []int{403}, Deterministic: false, Where: "Authority"},
	{Code: NoRegistration, Kind: KindServer, Statuses: []int{403}, Deterministic: false, Where: "Authority"},
	{Code: NoVaultRecord, Kind: KindServer, Statuses: []int{404}, Deterministic: false, Where: "Keys"},
	{Code: NonZeroPadding, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: NotFound, Kind: KindServer, Statuses: []int{404}, Deterministic: true, Where: "Compat"},
	{Code: OwnerGrantRequiresRoot, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: OwnerRevokeRequiresRoot, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: PayloadOverrunsBody, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: PruneDuplicateTarget, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: PruneExtNameMismatch, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: PruneExtWrongClass, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: PruneRepriseNotFound, Kind: KindServer, Statuses: []int{422}, Deterministic: false, Where: "Log"},
	{Code: PruneTargetAlreadyReprised, Kind: KindServer, Statuses: []int{422}, Deterministic: false, Where: "Log"},
	{Code: PruneTargetAttestationMismatch, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: PruneTargetIsControl, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: PruneTargetIsItsOwnReprise, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: PruneTargetIsPrune, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: PruneTargetIsServerRead, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: PruneTargetNotFound, Kind: KindServer, Statuses: []int{422}, Deterministic: false, Where: "Log"},
	{Code: PruneTargetsEmpty, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: PruneTargetsTooMany, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: RequestTooLarge, Kind: KindServer, Statuses: []int{413}, Deterministic: true, Where: "Compat"},
	{Code: RoleForbidsOpClass, Kind: KindServer, Statuses: []int{403}, Deterministic: false, Where: "Authority"},
	{Code: RoleForbidsPruneType, Kind: KindServer, Statuses: []int{403}, Deterministic: false, Where: "Authority"},
	{Code: RotateEpochConflict, Kind: KindServer, Statuses: []int{409}, Deterministic: false, Where: "Keys"},
	{Code: RotateNotMaterialised, Kind: KindServer, Statuses: []int{409}, Deterministic: false, Where: "Keys"},
	{Code: StoreUnavailable, Kind: KindServer, Statuses: []int{503}, Deterministic: false, Where: "Compat"},
	{Code: TruncatedEnvelope, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: UnknownDelegation, Kind: KindServer, Statuses: []int{422}, Deterministic: false, Where: "Authority"},
	{Code: UnknownGrant, Kind: KindServer, Statuses: []int{422}, Deterministic: false, Where: "Authority"},
	{Code: UnknownGrantee, Kind: KindServer, Statuses: []int{422}, Deterministic: false, Where: "Authority"},
	{Code: UnknownKeywrapMember, Kind: KindServer, Statuses: []int{422}, Deterministic: false, Where: "Keys"},
	{Code: UnknownMember, Kind: KindServer, Statuses: []int{404}, Deterministic: false, Where: "Identity"},
	{Code: UnknownMemberKind, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: UnknownRequestField, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Compat"},
	{Code: UnknownRole, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: UnsupportedContractVersion, Kind: KindServer, Statuses: []int{404}, Deterministic: true, Where: "Compat"},
	{Code: UnsupportedControlType, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Authority"},
	{Code: UnsupportedExtBindingType, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: UnsupportedOpClass, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: UnsupportedPruneType, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: UnsupportedSuite, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: VaultFetchRateLimited, Kind: KindServer, Statuses: []int{429}, Deterministic: false, Where: "Keys"},
	{Code: VaultRequiresGenesis, Kind: KindServer, Statuses: []int{403}, Deterministic: false, Where: "Identity"},
	{Code: VaultVersionRegression, Kind: KindServer, Statuses: []int{409}, Deterministic: true, Where: "Keys"},
	{Code: WorkspaceMismatch, Kind: KindServer, Statuses: []int{422}, Deterministic: true, Where: "Log"},
	{Code: WorkspaceNotCreated, Kind: KindServer, Statuses: []int{409}, Deterministic: false, Where: "Authority"},
	{Code: WorkspaceNotReachable, Kind: KindServer, Statuses: []int{403}, Deterministic: true, Where: "Authority"},
	{Code: WorkspaceQuotaExhausted, Kind: KindServer, Statuses: []int{402}, Deterministic: false, Where: "Log"},
	{Code: BadSignature, Kind: KindClient, Statuses: nil, Deterministic: false, Where: "Log"},
	{Code: ControlTypeNotServed, Kind: KindClient, Statuses: nil, Deterministic: false, Where: "Authority"},
	{Code: UnknownAuthorKey, Kind: KindClient, Statuses: nil, Deterministic: false, Where: "Authority"},
	{Code: AeadFailure, Kind: KindClient, Statuses: nil, Deterministic: false, Where: "Keys"},
	{Code: PlaintextAtEncryptedEpoch, Kind: KindClient, Statuses: nil, Deterministic: false, Where: "Keys"},
}

var byCode = func() map[Code]Spec {
	m := make(map[Code]Spec, len(All))
	for _, s := range All {
		m[s.Code] = s
	}
	return m
}()

// Lookup returns what the document records about a code.
func Lookup(c Code) (Spec, bool) {
	s, ok := byCode[c]
	return s, ok
}

// Status returns the single HTTP status a code is raised under. The bool is
// false where the document gives it more than one, or none — those callers name
// the status themselves, because the code alone does not decide it.
func Status(c Code) (int, bool) {
	s, ok := byCode[c]
	if !ok || len(s.Statuses) != 1 {
		return 0, false
	}
	return s.Statuses[0], true
}
