// Command codesgen generates ../../../codes/codes.go from
// docs/reference/refusal-codes.md.
//
// The vocabulary is closed: "a code not listed here is not a code", and a server
// may not narrow one, merge two, or invent an unlisted one for a listed cause.
// Generating the package is what turns that from a rule somebody reviews into a
// rule the compiler holds — a handler cannot name a code the document does not
// carry, because the identifier does not exist.
//
// Run it with `make codes`. `make check` verifies the checked-in file is current.
package main

import (
	"fmt"
	"log"
	"os"
	"sort"
	"strconv"
	"strings"
)

type spec struct {
	Code          string
	Ident         string
	Kind          string // "Server" or "Client"
	Statuses      []int
	Deterministic bool
	Where         string
	Doc           string
}

// closeNames is the one place a human names the signal close codes. They are
// numbers on the wire and the document tables them by cause, so there is nothing
// to derive an identifier from.
var closeNames = map[int]string{
	4400: "CloseProtocolError",
	4401: "CloseInvalidToken",
	4403: "CloseNoMembership",
}

func main() {
	src := "docs/reference/refusal-codes.md"
	dst := "codes/codes.go"
	if len(os.Args) > 2 {
		src, dst = os.Args[1], os.Args[2]
	}

	raw, err := os.ReadFile(src)
	if err != nil {
		log.Fatal(err)
	}

	server, client, closes := parse(string(raw))
	if len(server) == 0 || len(client) == 0 || len(closes) == 0 {
		log.Fatalf("parsed %d server, %d client, %d close codes — the document's shape has moved",
			len(server), len(client), len(closes))
	}

	out := render(server, client, closes)
	if err := os.WriteFile(dst, []byte(out), 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %s: %d server, %d client, %d signal close codes\n",
		dst, len(server), len(client), len(closes))
}

func parse(doc string) (server, client []spec, closes []int) {
	section := ""
	for _, line := range strings.Split(doc, "\n") {
		if strings.HasPrefix(line, "## ") {
			switch strings.TrimSpace(strings.TrimPrefix(line, "## ")) {
			case "Server codes":
				section = "server"
			case "Client codes":
				section = "client"
			case "Signal close codes":
				section = "close"
			default:
				section = ""
			}
			continue
		}
		if section == "" || !strings.HasPrefix(strings.TrimSpace(line), "|") {
			continue
		}
		cells := splitRow(line)
		if len(cells) < 2 || cells[0] == "Code" || strings.HasPrefix(cells[0], "---") {
			continue
		}
		name := unTick(cells[0])

		switch section {
		case "server":
			if len(cells) < 6 {
				continue
			}
			s := spec{
				Code:          name,
				Ident:         identOf(name),
				Kind:          "Server",
				Statuses:      statuses(cells[1]),
				Deterministic: strings.EqualFold(strings.TrimSpace(cells[4]), "yes"),
				Where:         strings.TrimSpace(cells[5]),
				Doc:           plain(cells[2]),
			}
			server = append(server, s)
		case "client":
			if len(cells) < 3 {
				continue
			}
			client = append(client, spec{
				Code:  name,
				Ident: identOf(name),
				Kind:  "Client",
				Where: strings.TrimSpace(cells[2]),
				Doc:   plain(cells[1]),
			})
		case "close":
			n, err := strconv.Atoi(name)
			if err != nil {
				continue
			}
			closes = append(closes, n)
		}
	}
	return server, client, closes
}

func splitRow(line string) []string {
	line = strings.TrimSpace(line)
	line = strings.TrimPrefix(line, "|")
	line = strings.TrimSuffix(line, "|")
	parts := strings.Split(line, "|")
	for i := range parts {
		parts[i] = strings.TrimSpace(parts[i])
	}
	return parts
}

func unTick(s string) string { return strings.Trim(strings.TrimSpace(s), "`") }

// plain strips the document's emphasis so a cell reads as a Go doc comment.
func plain(s string) string {
	r := strings.NewReplacer("**", "", "`", "", "…", "...")
	return strings.TrimSpace(r.Replace(s))
}

func statuses(cell string) []int {
	var out []int
	for _, p := range strings.Split(cell, ",") {
		n, err := strconv.Atoi(strings.TrimSpace(p))
		if err != nil {
			continue
		}
		out = append(out, n)
	}
	sort.Ints(out)
	return out
}

// identOf turns a snake_case code into a Go identifier. The codes are the
// document's; the identifiers are only how Go spells them.
func identOf(code string) string {
	var b strings.Builder
	for _, part := range strings.Split(code, "_") {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}

func render(server, client []spec, closes []int) string {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	p("// Code generated by internal/codegen/codesgen. DO NOT EDIT.")
	p("//")
	p("// Source: docs/reference/refusal-codes.md")
	p("")
	p("// Package codes is the closed refusal vocabulary.")
	p("//")
	p("// A code not in the document is not a code. It may not be narrowed, merged with")
	p("// another, or invented locally for a listed cause, and a client that meets one it")
	p("// does not recognise surfaces it verbatim rather than folding it into another's")
	p("// meaning. Generating this package from the document is what makes the closure")
	p("// mechanical: a handler cannot name a code the vocabulary does not carry.")
	p("package codes")
	p("")
	p("// Code is a stable machine-readable refusal name, carried as detail.code.")
	p("type Code string")
	p("")
	p("// Kind says which party raises a code.")
	p("type Kind uint8")
	p("")
	p("const (")
	p("\t// KindServer codes are raised by the server, against a request.")
	p("\tKindServer Kind = iota")
	p("\t// KindClient codes are raised by a device against bytes it pulled, never by")
	p("\t// the server. They are here because the vocabulary is shared.")
	p("\tKindClient")
	p(")")
	p("")
	p("// Spec is what the document records about one code.")
	p("type Spec struct {")
	p("\tCode Code")
	p("\tKind Kind")
	p("\t// Statuses is every HTTP status this code is raised under, ascending. Empty")
	p("\t// for client codes, which never travel on a response.")
	p("\tStatuses []int")
	p("\t// Deterministic reports whether a retry can change the outcome. A client")
	p("\t// terminalises a deterministic refusal rather than re-attempting it for ever.")
	p("\t// Defined for server codes.")
	p("\tDeterministic bool")
	p("\t// Where is the layer that specifies the rule.")
	p("\tWhere string")
	p("}")
	p("")

	p("// Server codes.")
	p("const (")
	for _, s := range server {
		p("\t// %s: %s", s.Ident, s.Doc)
		p("\t%s Code = %q", s.Ident, s.Code)
	}
	p(")")
	p("")

	p("// Client codes. Raised by a device against bytes it pulled, never by the server.")
	p("const (")
	for _, s := range client {
		p("\t// %s: %s", s.Ident, s.Doc)
		p("\t%s Code = %q", s.Ident, s.Code)
	}
	p(")")
	p("")

	p("// Signal close codes. A client's reconnect logic branches on these exact")
	p("// numbers, so they are protocol.")
	p("const (")
	for _, n := range closes {
		name, ok := closeNames[n]
		if !ok {
			log.Fatalf("signal close code %d has no identifier in codesgen's name map", n)
		}
		p("\t%s = %d", name, n)
	}
	p(")")
	p("")

	p("// All is every code the document carries, server codes first, each group in")
	p("// document order.")
	p("var All = []Spec{")
	for _, s := range append(append([]spec{}, server...), client...) {
		p("\t{Code: %s, Kind: Kind%s, Statuses: %s, Deterministic: %v, Where: %q},",
			s.Ident, s.Kind, goInts(s.Statuses), s.Deterministic, s.Where)
	}
	p("}")
	p("")

	p("var byCode = func() map[Code]Spec {")
	p("\tm := make(map[Code]Spec, len(All))")
	p("\tfor _, s := range All {")
	p("\t\tm[s.Code] = s")
	p("\t}")
	p("\treturn m")
	p("}()")
	p("")
	p("// Lookup returns what the document records about a code.")
	p("func Lookup(c Code) (Spec, bool) {")
	p("\ts, ok := byCode[c]")
	p("\treturn s, ok")
	p("}")
	p("")
	p("// Status returns the single HTTP status a code is raised under. The bool is")
	p("// false where the document gives it more than one, or none — those callers name")
	p("// the status themselves, because the code alone does not decide it.")
	p("func Status(c Code) (int, bool) {")
	p("\ts, ok := byCode[c]")
	p("\tif !ok || len(s.Statuses) != 1 {")
	p("\t\treturn 0, false")
	p("\t}")
	p("\treturn s.Statuses[0], true")
	p("}")

	return b.String()
}

func goInts(v []int) string {
	if len(v) == 0 {
		return "nil"
	}
	parts := make([]string, len(v))
	for i, n := range v {
		parts[i] = strconv.Itoa(n)
	}
	return "[]int{" + strings.Join(parts, ", ") + "}"
}
